name: patch-visualizer
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.10
  - pytorch==2.2.2
  - torchaudio==2.2.2
  - torchvision==0.17.2
  - pytorch-cuda=11.8
  - pyg
  - scipy
  - jupyterlab
  - pandas
  - pip
  - meshio
  - trimesh
  - lightning
  - pip:
    - -f https://data.pyg.org/whl/torch-2.2.0+cu118.html
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - numpy==1.26
    - gitpython
    - opencv-python
    - joblib
    - libigl
    - hydra-core
    - hydra-zen
    - imageio
    - open3d
    - pygltflib
    - rich
    - plyfile
    - polyscope
    - robust-laplacian
    - pymeshlab
    - triangle
    - noise
